### ISSUE TITLE
Error messaging does not provide enough info for the self-guided debug 

### ISSUE THREAD

**Issue by chili-chips-ba** [openXC7/nextpnr-xilinx#11]
"**Failed assert**" was reported for an issue that had nothing to do with assertions.
[https://symbioticeda.slack.com/archives/C053XV4R248/p1691040074754449](url)

We also strongly suggest adding switch for control of tool messaging verbosity level. This is even more important given the very limited openXC7 user base, hence no useful finds in Internet searches.

**Comment by hansfbaier** [comment]
@chili-chips-ba This link seems to be broken/lead to nothing anymore.
I know that the error messaging is not very good,
and I improved some. Do you still have concrete issues with this?
What are they?

**Comment by chili-chips-ba** [comment]
![image](https://github.com/user-attachments/assets/2a2a22fa-7bec-4a88-8150-18d55d02f3b5)

![image](https://github.com/user-attachments/assets/0c6672c9-74a1-4f76-9f5e-eedf5bedbbcb)

**Comment by hansfbaier** [comment]
Ok that one already has been fixed
