### ISSUE TITLE
Prioritize support of BSCANE2 and STARTUPE2 primitives

### ISSUE THREAD

**Issue by chili-chips-ba** [openXC7/nextpnr-xilinx#13]
With proliferation of SOC designs with on-chip CPUs, the selection of open-source RISC-V IP that can be used with openXC7 flow is severely limited due to lack of support for these two essential Xilinx primitives. That drastically affects openXC7 adoption rate, leaving it primarily to nerds and niche use-cases. E.g., the very popular Vex is not compatible with openXC7!

Even the essential PicoRV32 becomes problematic with openXC7 if one wants to deploy a serious and productive SW development flow for it. 

[https://symbioticeda.slack.com/archives/C053XV4R248/p1682539265405079](url)
[https://symbioticeda.slack.com/archives/C053XV4R248/p1686199192866639](url)

/* as a workaround for this openXC7 handicap, we've put together a UART-based solution for the live CPU program uploads, without having the rebuild the entire FPGA. While it worked for us, that's not sufficient for more complex apps, and also not compatible with GDB */

**Comment by hansfbaier** [comment]
This has been fixed. Both are implemented.
