### ISSUE TITLE
Update k325 branch of kintex-chatter prjxray-db repository to upstream

### ISSUE THREAD

**Issue by unbtorsten** [openXC7/nextpnr-xilinx#2]
For ease of development at this time, we change the submodule path to kintex-chatter's fork of prjxray-db, cf.
https://github.com/kintex-chatter/xc7k325t-blinky-nextpnr/issues/18
and #1.

Once k325t becomes part of the upstream prxjray-db, we should revert the changes of #1 and https://github.com/kintex-chatter/nextpnr-xilinx/commit/3165a86527e997416de0f6569d8b35e244e34c5d

**Comment by hansfbaier** [comment]
This ticket is now obsolete, since we have toolchain-installer
and demo-projects, which supersedes the blinky project.
