### ISSUE TITLE
nice to meet you

### ISSUE THREAD

**Issue by lehaifeng000** [openXC7/nextpnr-xilinx#22]
I have implemented most primitives and prjxray info of the XC7 devices using the f4pga-arch-defs project. but I've encountered some challenging issues with VPR, and Xilinx's architecture doesn't seem to fit well with VPR either. I am planning to try nextpnr next. I have forked your project. would it be possible to reach out to you if I encounter any issues in the future?

**Comment by hansfbaier** [comment]
Yes, of course, I suggest we work closely together to avoid duplicated effort.
What are your goals?
What are you going to work on next?

**Comment by hansfbaier** [comment]
I am currently working on GTP Transceiver support.

**Comment by lehaifeng000** [comment]
thank you, I want to start by adding FIFO18E1, and in the process, familiarize myself with the nextpnr codebase.

**Comment by hansfbaier** [comment]
That is a welcome addition, I think we don't have that yet.
Don't hesitate to ask questions.
We can also do a video call, if you want me to show you around and explain the big picture.

**Comment by lehaifeng000** [comment]
thank you!

**Comment by hansfbaier** [comment]
I think this issue is done than.
Let me know when you have issues.

**Comment by lehaifeng000** [comment]
no, thanks!
