### ISSUE TITLE
nextpnr-xilinx crash when MONITOR_BOT_XXX pin is used as input or output data PAD

### ISSUE THREAD

**Issue by mirekez** [openXC7/nextpnr-xilinx#36]
using MONITORING PIN gives a crash:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
make: *** [../openXC7.mk:44: Test.fasm] Aborted (core dumped)
```
or
```
Info: Generating input buffer for '$iopadmap$Test.a'
Info:     Created 69 PAD cells from:
Info:             69x PAD
Info: Preparing clocking...
terminate called after throwing an instance of 'std::out_of_range'
  what():  dict::at()
Aborted (core dumped)
```

pin like
J10,0,IPAD_X0Y30,MONITOR_BOT_X46Y131,VP_0 
for
xc7a100tcsg324-2

[terminate_called_after_throwing_an_instance_of_std_out_of_range.zip](https://github.com/user-attachments/files/16677235/terminate_called_after_throwing_an_instance_of_std_out_of_range.zip)

**Comment by hansfbaier** [comment]
Vivado cannot do it either, but it has a nice error message
![20240821_02h53m23s_grim](https://github.com/user-attachments/assets/162505e6-e285-4ea1-8ed8-7bb19a19aaf2)
