### ISSUE TITLE
Why do we need to divide the offset by 4?

### ISSUE THREAD

**Issue by AdamLee7** [openXC7/nextpnr-xilinx#58]
![image](https://github.com/user-attachments/assets/78aa496a-5015-49c5-9198-8afb95b138e1)
@hansfbaier Why do we divide offset by 4 in bba and restore it in RelPtr? Is there any benefit in this?

**Comment by hansfbaier** [comment]
I think it is because the address addresses 32 bit words which is 4 bytes.
