### ISSUE TITLE
Add support for pin drive strength

### ISSUE THREAD

**Issue by Tobias-DG3YEV** [openXC7/nextpnr-xilinx#7]
Please add support for pin drive strength.
This is set with "set_property DRIVE" in the .xdc file.

Currently nextpnr-xilinx only give an assertion, when it finds such entry in the xdc.

``
what():  Assertion failure: !is_string (/home/tobiw/nextpnr/tmp/nextpnr-xilinx/common/nextpnr.h:350)
make: *** [Makefile:29: spec2g4.fasm] Aborted
``

**Comment by cestrauss** [comment]
I traced it back to https://github.com/openXC7/nextpnr-xilinx/blob/159aaa86cb3a12c4a9638830b562e57fdcba28c4/xilinx/pack_io_xc7.cc#L458

It seems the Property value is stored as a string, not as an integer. The as_int64() method does not actually do an automatic conversion from string to integer, raising an exception instead.
